#!/bin/sh
set -e

test "$1" = 'configure' || exit 0

# enable git-daemon service
update-service --add /etc/sv/shelper

# restart shelper service if it was running
test -z "$2" || sv -v term shelper || :
